### ISSUE TITLE
Printouts during async call causes corrupted Robot report file

### ISSUE THREAD

**Issue by AndersKOlsson** [Chetic/robotframework-async#2]
We have seen undeterministic behavior when using the "Async Run" keyword. Sometimes the output.xml get corrupted. Run the exact same test again, and everything is fine.

We've narrowed this down to <msg> tags placed spuriously, in the cases we've been able to see. The sometimes failing sequence is:
-Async Run KW
-KW that does a 'print'

It seems Robot gets very confused about what's happening where, and gladly outputs a 'msg' element into an 'arguments' element (which is not allowed by the schema) of the KW element running async, making things very confused.

Is there some general warning about only using AsyncLibrary in some constrained ways?

I'm raising this as a generic threading issue in the Robot Framework tracker as well.

**Comment by AndersKOlsson** [comment]
Having further studied this, I notice that the behavior of 'Async Run' is Logging is disabled for that keyword (as a safety mechanism?). But, if a library uses 'print' that's where things seem to go crazy. The output normally goes to the KW executing in the main thread (and sometimes to the screen), but on the rare occasion, it goes right into the middle of a element being logged, as if the whole Robot logging framework was completely thread-unsafe.

It seems safe to say that it's advisable to to ruin an KW that uses print as async.

**Comment by AndersKOlsson** [comment]
I made a simple example to illustrate this. This can also cause the race condition problem, where the 'msg' log element goes to the wrong place.

asynctest.py:
import time
from robot.api import logger

class asynctest:
    def **init**(self):
        pass
    def my_asynctest(self, msg, wait=0.001, repeat=10000):
        for i in range(int(repeat)):
            if wait:
                time.sleep(float(wait))
            print "Print ", msg
            logger.info("Log " + msg)

asynctest.robot:
**_Settings**_
Library  AsyncLibrary
Library  asynctest.py

**_Keywords**_
My Test
    [Arguments]  ${num}
    Log  ${num}
    Sleep  ${num} seconds
    Log  ${num}
    Sleep  ${num} seconds
    Log  ${num}
    Sleep  ${num} seconds

**_Testcases**_
Local Test
    Async Run  My Test  2
    My Test  1
    Sleep  5 seconds

Lib Test
    Async Run  My Asynctest  Async
    Sleep  10 ms
    Sleep  10 ms
    Sleep  10 ms
    Sleep  10 ms
    My Asynctest  Sync  0.02  1000
    Sleep  1 seconds

**Comment by Chetic** [comment]
Sounds like a Robot Framework issue. Does this happen on newer releases as well?

**Comment by AndersKOlsson** [comment]
I have no idea. I'm not using the framework anymore. Think a new bug should be raised, if users are having the issue still.

**Comment by rlehfeld** [comment]
this is no RobotFramework problem. RobotFramework is not supporting multithreaded execution of keywords or in other words, it is not expecting that keywords are executed outside of the main thread BUT I also find this usefull. Due to that I was working on an advanced solution and forked the repo. It is working in my use cases now.
You can find my fork here https://github.com/rlehfeld/robotframework-async-keyword.git
